version: '3.5'

services:
  app:
    build:
      context: ./docker
    user: "1000:1001"
    volumes:
      - ../:/var/www/html
    ports:
      - '80:80'
    working_dir: /var/www/html
    command: >
      bash -c "apache2-foreground && \
              chown 1000:1001 -R /var/www/html"